[pytest]
markers =
    slow: Marks tests as slow running (deselect with '-m "not slow"')

addopts =
    --capture=no
    --cov=aiotimer
    --cov-branch
    --cov-report=xml
    --strict-config
    --strict-markers

asyncio_mode = strict
asyncio_debug = true
